// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptgmuygfahynmydfgdtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0Z211eWdmYWh5bm15ZGZnZHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODI0ODYsImV4cCI6MjA2NDc1ODQ4Nn0.fbRVv4KRQo4KcvooP0XSt6mo34Z-mWk_ER9ki8-VkPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);